name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install debootstrap python3-venv make
        python -m pip install --upgrade pip
        make dev
    #- name: Lint with flake8
    #  run: |
    #    make cs
    #    make lint
    - name: Test with pytest
      run: |
        make check
